version: '3'

services:
  weblog_mail:
    container_name: weblog_mail
    build: ./node
    tty: true
    ports:
      - 9000:9000
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    volumes:
      - ./app:/app
