service: weblog-mail

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  timeout: 30
  memorySize: 128
  # 特定の許可ステートメントを設定
  # SESをLambdaから使うには上記の記述が必要
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - ses:SendEmail
      Resource: '*'
  # CloudWatch Logsの有効期限を設定する
  logRetentionInDays: 7

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  sendMail:
    handler: src/handler.sendMail
    events:
      - http:
          method: post
          path: send-mail
          cors: true

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9000
