service: weblog-mail

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  timeout: 30

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9000
