service: weblog-mail

useDotenv: true

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  timeout: 30
  memorySize: 128
  # 特定の許可ステートメントを設定
  # SESをLambdaから使うには下記の記述が必要
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - ses:SendEmail
          Resource: '*'
  # CloudWatch Logsの有効期限を設定する
  logRetentionInDays: 7
  # Starting with v3.0.0, API Gateway naming will be changed from ${stage}-${service} to ${service}-${stage}.
  # https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
  apiGateway:
    shouldStartNameWithService: true
  # オプション
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  sendMail:
    handler: src/handler.sendMail
    environment:
      RECAPTCHA_KEY: ${env:RECAPTCHA_KEY}
    events:
      - http:
          method: post
          path: send-mail
          cors:
            origins:
              - https://karukichi-blog.netlify.app
              - https://staging--karukichi-blog.netlify.app
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9000
